columns = [
['Unnamed: 0.3'],
['Unnamed: 0.2'],
['Unnamed: 0.1'],
['Unnamed: 0'],
['elapsed_sec'],
['_time'],
['N1'],
['N2'],
['PR'],
['Turbine_Exit'],
['Power'],
['Elapsed Time (s)'],
['Index'],
['Channel_(Time)'],
['N1_Speed_([krpm])'],
['N2_Speed_([krpm])'],
['N2_Raw_avg_([krpm])'],
['Ch1_RMS_([m/s2])'],
['Ch2_RMS_([m/s2])'],
['Ch1_Crest_Factor_([-])'],
['Ch2_Crest_Factor_([-])'],
['P_NI_Box_(P)'],
['T_NI_Box_(C)'],
['P_Oil_(psi)'],
['P_TM_Cooling_Snake_(psi)'],
['P_Fuel_(psi)'],
['P_Inlet_Mass_Flow_1_(Pa)'],
['P_Inlet_Mass_Flow_2_(Pa)'],
['P_PT_Exit_Flow_Pressure_5_(Pa)'],
['P_Combustor_(Pa)'],
['P_Impeller_Discharge_1_(Pa)'],
['P_Impeller_Discharge_2_(Pa)'],
['P_Impeller_Discharge_3_(Pa)'],
['P_Impeller_Discharge_4_(Pa)'],
['P_LSSP_Inlet_1_(Pa)'],
['P_LSSP_Inlet_3_(Pa)'],
['P_LSSP_Outlet_1_(Pa)'],
['P_LSSP_Outlet_3_(Pa)'],
['F_Axial_(N)'],
['T_Gen_Embedded_pt_1_(C)'],
['T_Gen_Embedded_pt_2_(C)'],
['T_Gen_Fluid_in_ntc_(C)'],
['T_Gen_Fluid_out_ntc_(C)'],
['N2_Banner_ai_(krpm)'],
['N2_Reluctance_ai_(krpm)'],
['T_Inlet_Air_(C)'],
['T_Combustor_Can_Boot_(C)'],
['T_Combustor_Cap_(C)'],
['T_Seal_Bypass_Flow_1_(C)'],
['T_Seal_Bypass_Flow_2_(C)'],
['T_Turbine_Exit_Flow_(C)'],
['T_Oil_Inlet_Flow_(C)'],
['T_Oil_Outlet_Flow_(C)'],
['T_TM_Cooling_Snake_In_(C)'],
['T_TM_Cooling_Snake_Out_(C)'],
['T_Heat_Shield_Cavity_(C)'],
['T_Combustor_Can_Surface_1_(C)'],
['T_Combustor_Can_Surface_2_(C)'],
['T_Hot_Section_Housing_1_(C)'],
['T_Hot_Section_Housing_2_(C)'],
['T_Oil_Sump_Vent_Temperature_(C)'],
['T_Cross_Duct_Flow_1_(C)'],
['T_Cross_Duct_Flow_3_(C)'],
['T_Cross_Duct_Flow_5_(C)'],
['T_Turbine_Exit_Flow_4_(C)'],
['t_stamp'],
['atmospheric pressure'],
['bearing temperature'],
['co2 pressure'],
['co2 temperature'],
['fuel inlet pressure'],
['fuel inlet temperature'],
['fuel regulator'],
['fuel supply pressure'],
['generator case temperature 1'],
['generator case temperature 2'],
['generator case temperature 3'],
['generator case temperature 4'],
['generator outlet temperature'],
['generator phase1 current'],
['generator phase1 voltage'],
['generator phase2 current'],
['generator phase2 voltage'],
['generator phase3 current'],
['generator phase3 voltage'],
['inlet static pressure'],
['inlet temperature'],
['n1 speed sensor'],
['n2 speed sensor'],
['oil pressure'],
['oil temperature'],
['pt outlet pressure 1'],
['pt outlet pressure 2'],
['pt outlet pressure 3'],
['pt outlet pressure 4'],
['pt outlet temperature 1'],
['pt outlet temperature 2'],
['pt outlet temperature 3'],
['pt outlet temperature 4'],
['turbine outlet temperature 1'],
['turbine outlet temperature 2'],
['relay_st1'],
['relay_st2'],
['relay_st3'],
['relay_st4'],
['relay_st5'],
['n2b speed sensor'],
['GenV'],
['GenI'],
]
