columns = [
    ["Unnamed: 0.3"],
    ["Unnamed: 0.2"],
    ["Unnamed: 0.1"],
    ["Unnamed: 0"],
    ["elapsed_sec"],
    ["_time"],
    ["N1"],
    ["N2"],
    ["PR"],
    ["Turbine_Exit"],
    ["Power"],
    ["Index"],
    ["Elapsed Time (s)"],
    ["Channel_NI"],
    ["Ch1 RMS_NI"],
    ["Ch2 RMS_NI"],
    ["Ch1 Crest Factor_NI"],
    ["Ch2 Crest Factor_NI"],
    ["P_NI_Box_NI"],
    ["T_NI_Box_NI"],
    ["P_Oil_NI"],
    ["P_TM_Cooling_Snake_NI"],
    ["P_Fuel_NI"],
    ["P_Inlet_Mass_Flow_1_NI"],
    ["P_Inlet_Mass_Flow_2_NI"],
    ["P_PT_Exit_Flow_Pressure_5_NI"],
    ["P_Combustor_NI"],
    ["P_Impeller_Discharge_1_NI"],
    ["P_Impeller_Discharge_2_NI"],
    ["P_Impeller_Discharge_3_NI"],
    ["P_Impeller_Discharge_4_NI"],
    ["P_LSSP_Inlet_1_NI"],
    ["P_LSSP_Inlet_3_NI"],
    ["P_LSSP_Outlet_1_NI"],
    ["P_LSSP_Outlet_3_NI"],
    ["F_Axial_NI"],
    ["T_Gen_Embedded_pt_1_NI"],
    ["T_Gen_Embedded_pt_2_NI"],
    ["T_Gen_Fluid_in_ntc_NI"],
    ["T_Gen_Fluid_out_ntc_NI"],
    ["N2_Banner_ai_NI"],
    ["N2_Reluctance_ai_NI"],
    ["N1_ai_NI"],
    ["T_Inlet_Air_NI"],
    ["T_Combustor_Can_Boot_NI"],
    ["T_Combustor_Cap_NI"],
    ["T_Seal_Bypass_Flow_1_NI"],
    ["T_Seal_Bypass_Flow_2_NI"],
    ["T_Turbine_Exit_Flow_NI"],
    ["T_Oil_Inlet_Flow_NI"],
    ["T_Oil_Outlet_Flow_NI"],
    ["T_TM_Cooling_Snake_In_NI"],
    ["T_TM_Cooling_Snake_Out_NI"],
    ["T_Heat_Shield_Cavity_NI"],
    ["T_Combustor_Can_Surface_1_NI"],
    ["T_Combustor_Can_Surface_2_NI"],
    ["T_Hot_Section_Housing_1_NI"],
    ["T_Hot_Section_Housing_2_NI"],
    ["T_Oil_Sump_Vent_Temperature_NI"],
    ["T_Cross_Duct_Flow_1_NI"],
    ["T_Cross_Duct_Flow_3_NI"],
    ["T_Cross_Duct_Flow_5_NI"],
    ["T_Turbine_Exit_Flow_4_NI"],
    ["Water_dt_C_NI"],
    ["atmospheric pressure_PLC"],
    ["bearing temperature_PLC"],
    ["co2 temperature_PLC"],
    ["fuel inlet pressure_PLC"],
    ["fuel inlet temperature_PLC"],
    ["fuel regulator_PLC"],
    ["fuel supply pressure_PLC"],
    ["generator case temperature 1_PLC"],
    ["generator case temperature 2_PLC"],
    ["generator case temperature 3_PLC"],
    ["generator case temperature 4_PLC"],
    ["generator outlet temperature_PLC"],
    ["generator phase1 current_PLC"],
    ["generator phase1 voltage_PLC"],
    ["generator phase2 current_PLC"],
    ["generator phase2 voltage_PLC"],
    ["generator phase3 current_PLC"],
    ["generator phase3 voltage_PLC"],
    ["inlet static pressure_PLC"],
    ["inlet temperature_PLC"],
    ["n1 speed sensor_PLC"],
    ["n2 speed sensor_PLC"],
    ["oil pressure_PLC"],
    ["oil temperature_PLC"],
    ["pt outlet pressure 1"],
    ["pt outlet pressure 2_PLC"],
    ["pt outlet pressure 3_PLC"],
    ["pt outlet pressure 4_PLC"],
    ["pt outlet temperature 1_PLC"],
    ["pt outlet temperature 2_PLC"],
    ["pt outlet temperature 3_PLC"],
    ["pt outlet temperature 4_PLC"],
    ["turbine outlet temperature 1_PLC"],
    ["turbine outlet temperature 2_PLC"],
    ["relay_st1_PLC"],
    ["relay_st2_PLC"],
    ["relay_st3_PLC"],
    ["relay_st4_PLC"],
    ["relay_st5_PLC"],
    ["n2b analog_PLC"],
    ["n2b speed sensor_PLC"],
    ["Power [kW]"],
    ["Power(kW)_PLC"],
]
